server:
  port: 0
spring:
  application:
    name: service-one
  datasource:
    url: jdbc:mysql://localhost/service_one?createDatabaseIfNotExist=true
    username: root
    password: root
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9000/auth/oauth/check_token
    client:
      client-id: auth-api
      client-secret: a1b2c3
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost
